### ISSUE TITLE
Can not access to settings

### ISSUE THREAD

**Issue by beudbeud** [trigg/Discover#102]
Hi when i try to get access to settings i get traceback

```
Traceback (most recent call last):
  File "/home/adrien/.local/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 166, in entrypoint
    Discover(rpc_file, line)
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 51, in __init__
    self.do_args(args)
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 64, in do_args
    self.show_settings()
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 137, in show_settings
    self.settings.present_settings()
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/settings_window.py", line 70, in present_settings
    self.text_settings.present_settings()
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/text_settings.py", line 158, in present_settings
    self.connector.request_text_rooms_for_guild(self.guild)
  File "/home/adrien/.local/lib/python3.8/site-packages/discover_overlay/discord_connector.py", line 617, in request_text_rooms_for_guild
    None] * len(self.guilds[guild_id]["channels"])
KeyError: '0'
```

**Comment by trigg** [comment]
Thanks for the report. Totally missed this one!
