### ISSUE TITLE
NameError: name 'GtkLayerShell' is not defined

### ISSUE THREAD

**Issue by PopeRigby** [trigg/Discover#105]
I'm getting this when trying to run Discover on Sway + Arch Linux. I have `python-gobject` installed, so I don't know what's up.

**Comment by trigg** [comment]
Could I please get the whole error message as it'll help me find where the error is.

**Comment by PopeRigby** [comment]
Sorry. Here it is:
```
Traceback (most recent call last):
  File "/usr/bin/discover-overlay", line 33, in <module>
    sys.exit(load_entry_point('discover-overlay==0.3.3', 'console_scripts', 'discover-overlay')())
  File "/usr/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 166, in entrypoint
    Discover(rpc_file, line)
  File "/usr/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 40, in __init__
    self.create_gui()
  File "/usr/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 81, in create_gui
    self.voice_overlay = VoiceOverlayWindow(self)
  File "/usr/lib/python3.8/site-packages/discover_overlay/voice_overlay.py", line 24, in __init__
    OverlayWindow.__init__(self)
  File "/usr/lib/python3.8/site-packages/discover_overlay/overlay.py", line 83, in __init__
    self.set_wayland_state()
  File "/usr/lib/python3.8/site-packages/discover_overlay/overlay.py", line 99, in set_wayland_state
    GtkLayerShell.init_for_window(self)
NameError: name 'GtkLayerShell' is not defined
```

**Comment by trigg** [comment]
Got it, So I don't know how sway doesn't end up pulling in gtk-layer-shell but looks like you're missing the pacman package `gtk-layer-shell`

apologies, I thought that would have to be included.

**Comment by PopeRigby** [comment]
That did it, thanks. Should that be put somewhere in the README?

**Comment by trigg** [comment]
I did directly after my reply to you! Glad we worked it out.

**Comment by hlieberman** [comment]
I'm seeing this same behavior.  Debian testing, verified the libgtk-layer-shell0 is installed.

```
Traceback (most recent call last):
  File "/home/hlieberman/.local/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/hlieberman/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 167, in entrypoint
    Discover(rpc_file, line)
  File "/home/hlieberman/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 40, in __init__
    self.create_gui()
  File "/home/hlieberman/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 81, in create_gui
    self.voice_overlay = VoiceOverlayWindow(self)
  File "/home/hlieberman/.local/lib/python3.8/site-packages/discover_overlay/voice_overlay.py", line 24, in __init__
    OverlayWindow.__init__(self)
  File "/home/hlieberman/.local/lib/python3.8/site-packages/discover_overlay/overlay.py", line 83, in __init__
    self.set_wayland_state()
  File "/home/hlieberman/.local/lib/python3.8/site-packages/discover_overlay/overlay.py", line 99, in set_wayland_state
    GtkLayerShell.init_for_window(self)
NameError: name 'GtkLayerShell' is not defined```

**Comment by martinarcola** [comment]
I'm also seeing the same error and stack trace as @hlieberman above, on Debian testing, libgtk-layer-shell0 0.5.2-1 installed from apt.
This is for v0.3.3 of the overlay installed by pip.
(I installed python3-gi 3.38.0-1+b2 from apt first)

Could you please re-open the issue?
