### ISSUE TITLE
AttributeError: module 'pidfile' has no attribute 'AlreadyRunningError'

### ISSUE THREAD

**Issue by Joshix-1** [trigg/Discover#106]
```
discover-overlay
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 132, in entrypoint
    with pidfile.PIDFile(pid_file):
AttributeError: module 'pidfile' has no attribute 'PIDFile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 135, in entrypoint
    except pidfile.AlreadyRunningError:
AttributeError: module 'pidfile' has no attribute 'AlreadyRunningError'
```

reinstalled with:
`python3 -m pip uninstall discover-overlay`
`python3 -m pip install discover-overlay`

It worked before. I'm using Arch Linux.
![image](https://user-images.githubusercontent.com/57299889/97360206-29cafb80-189e-11eb-809e-3b21e97a9d20.png)

**Comment by trigg** [comment]
this is odd as it is clearly finding pidfile itself...

`python3 -m pip uninstall python-pidfile` and then install again after?

**Comment by Joshix-1** [comment]
works now, thx
