### ISSUE TITLE
Python-gi issues 

### ISSUE THREAD

**Issue by trigg** [trigg/Discover#111]
Have the same issue, after updating to python3.8 I get the following error:
```Traceback (most recent call last):
 File "./discover-overlay", line 5, in <module>   from discover_overlay.discover_overlay import entrypoint
   File "/home/username/.local/lib/python3.8/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/username/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 17, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

After following [Stackoverflow](https://stackoverflow.com/questions/59838238/importerror-cannot-import-name-gi-from-partially-initialized-module-gi-mo) and replacing `import gi`
with 
`import pgi
pgi.install_as_gi()
from gi.repository import GLib, Gio` 
in discover-overlay.pi I receive this error, which I can't make heads or tails of.

`Traceback (most recent call last):
  File "./discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/home/username/.local/lib/python3.8/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/username/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 21, in <module>
    import pidfile
  File "/home/username/.local/lib/python3.8/site-packages/pidfile/__init__.py", line 1, in <module>
    from .pidfile import PIDFile, AlreadyRunningError
  File "/home/username/.local/lib/python3.8/site-packages/pidfile/pidfile.py", line 2, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)
`

At this point first a giant thanks to you, I and I think we all thank you a lot for your work!

_Originally posted by @Mxtreme1 in https://github.com/trigg/Discover/issues/58#issuecomment-724053222_

**Comment by trigg** [comment]
So this looks like a python-gi issue. I'd strongly advise installing your distro version of python-gi instead.

First up what's your distro, and which method are you using to install discover?

**Comment by Mxtreme1** [comment]
Also using Ubuntu 18.04 Budgie flavour.

**Comment by Mxtreme1** [comment]
Ill try that, I used both the git clone and direct pip install.

**Comment by trigg** [comment]
Fair. While technically PIP can install python-gi I've not once seen it cope with the task.

**Comment by Mxtreme1** [comment]
Oh beg pardon if I was unclear, I meant that I used both `python3 -m pip install discover-overlay` and
```
git clone https://github.com/trigg/Discover.git
cd Discover
python3 -m pip install .
```
to install discover.

I used apt to install python3-gi.

**Comment by trigg** [comment]
Ah, no I understood what you meant! The readme has a dependency section below install that explains how to get python-gi on debian/ubuntu. Do that, and try a fresh unedited install again :)

**Comment by Mxtreme1** [comment]
Figured it out. Reverted back to python 3.6 and got the same error as [issue #58](https://github.com/trigg/Discover/issues/58),
but for me changing line 151 in discord_connector.py to the following worked.
It is exactly what the link in that issue recommended. [Stackoverflow](https://stackoverflow.com/questions/53291250/python-3-6-datetime-strptime-returns-error-while-python-3-7-works-well)
```
        utc_time = time.strptime(
            message["timestamp"], "%Y-%m-%dT%H:%M:%S.%fz")
```
