### ISSUE TITLE
I don't know

### ISSUE THREAD

**Issue by DJFiBePRO** [trigg/Discover#116]
carlos@Fialloslx-PC:~$ ~/.local/bin/discover-overlay
Traceback (most recent call last):
  File "/home/carlos/.local/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/carlos/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 166, in entrypoint
    Discover(rpc_file, line)
  File "/home/carlos/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 40, in __init__
    self.create_gui()
  File "/home/carlos/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 81, in create_gui
    self.voice_overlay = VoiceOverlayWindow(self)
  File "/home/carlos/.local/lib/python3.8/site-packages/discover_overlay/voice_overlay.py", line 24, in __init__
    OverlayWindow.__init__(self)
  File "/home/carlos/.local/lib/python3.8/site-packages/discover_overlay/overlay.py", line 77, in __init__
    self.set_untouchable()
  File "/home/carlos/.local/lib/python3.8/site-packages/discover_overlay/overlay.py", line 141, in set_untouchable
    reg = Gdk.cairo_region_create_from_surface(surface)
KeyError: 'could not find foreign type Surface'

**Comment by midget3111** [comment]
Hey,
Could we have more info with this? Which version of Discover-Overlay are you trying to run and on what OS?
Do you get the same message by just running "discover-overlay" in terminal?

**Comment by trigg** [comment]
Fix Listed in #118
