### ISSUE TITLE
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mothringer** [trigg/Discover#124]
I'm receiving the below error running a freshly installed stable copy.

Traceback (most recent call last):
  File "./.local/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/home/mothringer/.local/lib/python3.8/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/mothringer/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 18, in <module>
    import pidfile
  File "/home/mothringer/.local/lib/python3.8/site-packages/pidfile/__init__.py", line 1, in <module>
    from .pidfile import PIDFile, AlreadyRunningError
  File "/home/mothringer/.local/lib/python3.8/site-packages/pidfile/pidfile.py", line 2, in <module>
    import psutil
  File "/home/mothringer/.local/lib/python3.8/site-packages/psutil/__init__.py", line 99, in <module>
    from . import _pslinux as _psplatform
  File "/home/mothringer/.local/lib/python3.8/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/home/mothringer/.local/lib/python3.8/site-packages/psutil/__init__.py)

**Comment by trigg** [comment]
What was your install method? Which OS?

It looks like psutil needs to be reinstalled/

**Comment by mothringer** [comment]
installed using pip install discover-overlay --user

uninstalling psutil and reinstalling it manually fixed it, so I guess something must've gone wrong silently when pip installed the dependencies initially
