### ISSUE TITLE
Program launches, but doesn't show icons when people speaking

### ISSUE THREAD

**Issue by unurled** [trigg/Discover#132]
```INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 0
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Loading saved channel 0
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Could not find monitor : None
INFO:root:Autostart info : desktop /home/$USER/.local/share/applications/discover_overlay.desktop auto None
Traceback (most recent call last):
  File "/home/$USER/.local/lib/python3.8/site-packages/discover_overlay/discord_connector.py", line 593, in do_read
    self.on_message(msg)
  File "/home/$USER/.local/lib/python3.8/site-packages/discover_overlay/discord_connector.py", line 254, in on_message
    j = json.loads(message)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

Additional information

    Discover version: 5f0d0d9

    Discord version:
        ```Canary 77996 (2b4da83)
         Host 0.0.119
         Linux 64-Bit (5.8.0-44-Generic)

**Comment by trigg** [comment]
Does this occur on non-Canary versions on Discord?

**Comment by unurled** [comment]
I havn't tested, gonna test rn
