### ISSUE TITLE
Error on trying to run

### ISSUE THREAD

**Issue by alexbrrsclnt** [trigg/Discover#15]
I installed correctly but when I run `discover-overlay` I get this error

```
$ discover-overlay 
Using XShape instead of composite
Traceback (most recent call last):
  File "/usr/local/bin/discover-overlay", line 1058, in <module>
    main()
  File "/usr/local/bin/discover-overlay", line 1039, in main
    create_gui()
  File "/usr/local/bin/discover-overlay", line 984, in create_gui
    win = OverlayWindow()
  File "/usr/local/bin/discover-overlay", line 649, in __init__
    self.set_untouchable()
  File "/usr/local/bin/discover-overlay", line 718, in set_untouchable
    reg = Gdk.cairo_region_create_from_surface(surface)
KeyError: 'could not find foreign type Surface'
```

**Comment by trigg** [comment]
So we're missing python-gi-cairo, which I would have expected to be present with gtk. What distro are you running?

**Comment by alexbrrsclnt** [comment]
KDE Neon (Ubuntu 20.04)

**Comment by trigg** [comment]
so I'm led to believe `sudo apt install python3-gi-cairo` is all you need. Let me know if it works afterwards

**Comment by alexbrrsclnt** [comment]
Yeah, that solves the issue, thank you very much!
