### ISSUE TITLE
Overlay fails to show up

### ISSUE THREAD

**Issue by alsoGAMER** [trigg/Discover#154]
Terminal output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/discover_overlay/settings.py", line 207, in change_align_x
    self.overlay.set_align_x(button.get_active() == 1)
  File "/usr/lib/python3.9/site-packages/discover_overlay/overlay.py", line 225, in set_align_x
    self.force_location()
  File "/usr/lib/python3.9/site-packages/discover_overlay/overlay.py", line 182, in force_location
    self.redraw()
  File "/usr/lib/python3.9/site-packages/discover_overlay/overlay.py", line 202, in redraw
    self.overlay_draw(None, surface_ctx)
  File "/usr/lib/python3.9/site-packages/discover_overlay/voice_overlay.py", line 287, in overlay_draw
    self.draw_avatar(context, user, current_y)
  File "/usr/lib/python3.9/site-packages/discover_overlay/voice_overlay.py", line 335, in draw_avatar
    context, user["friendlyname"],
KeyError: 'friendlyname'
```

**Comment by trigg** [comment]
Good afternoon!

How have you installed Discover, and what OS/Distro are you using?

**Comment by alsoGAMER** [comment]
> How have you installed Discover

Of course

> and what OS/Distro are you using?

Archlinux

**Comment by trigg** [comment]
> > How have you installed Discover
> 
> Of course

It would really help if we knew how you installed it. AUR, straight from git?

**Comment by alsoGAMER** [comment]
> > > How have you installed Discover
> > 
> > 
> > Of course
> 
> It would really help if we knew how you installed it. AUR, straight from git?

Aur, the discover-overlay package

**Comment by trigg** [comment]
Thank you. Could I suggest using discover-overlay-git as it's a newer version and will give tracebacks that match current code, allowing me to fix bugs.

**Comment by alsoGAMER** [comment]
> Thank you. Could I suggest using discover-overlay-git as it's a newer version and will give tracebacks that match current code, allowing me to fix bugs.

I've installed that version, now it's working fine

**Comment by trigg** [comment]
I'll close now, with a mention to @midget3111 that it's worth checking if we need another stable pushed
