### ISSUE TITLE
"friendlyname" not found

### ISSUE THREAD

**Issue by Joshix-1** [trigg/Discover#163]
I got the following error on the latest commit:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/discover_overlay/discord_connector.py", line 593, in do_read
    self.voice_overlay.set_connection(self.last_connection)
  File "/usr/lib/python3.9/site-packages/discover_overlay/voice_overlay.py", line 254, in set_connection
    self.redraw()
  File "/usr/lib/python3.9/site-packages/discover_overlay/overlay.py", line 207, in redraw
    self.overlay_draw(None, surface_ctx)
  File "/usr/lib/python3.9/site-packages/discover_overlay/voice_overlay.py", line 348, in overlay_draw
    self.draw_avatar(context, user, current_y)
  File "/usr/lib/python3.9/site-packages/discover_overlay/voice_overlay.py", line 432, in draw_avatar
    context, user["friendlyname"],
KeyError: 'friendlyname'
Exception in thread Thread-2:
```

**Comment by trigg** [comment]
I can't work out how it's getting past line 296

it should be set one way or the other

**Comment by Joshix-1** [comment]
I just tried to reproduce it, and it didn't happen.

**Comment by pbogut** [comment]
Happens to me as well. Not every time but it does.
