### ISSUE TITLE
Some weird error with drawing

### ISSUE THREAD

**Issue by Joshix-1** [trigg/Discover#176]
**Steps to Reproduce**
1. Start the program
2. Something with images

**Expected behavior**
shouldn't crash

**Ekzematic behavior**
error

**Desktop (please complete the following information):**
 - OS: Arch 

**Installation Method**
 - AUR (-git)

**Additional context**
error:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-11:
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/threading.py", line 910, in run
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/image_getter.py", line 82, in get_url
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 41 8192
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/image_getter.py", line 82, in get_url
    self.func(self.identifier, surface)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 162, in recv_attach
    self.redraw()
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/overlay.py", line 226, in redraw
    self.func(self.identifier, surface)
    self._target(*self._args, **self._kwargs)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/image_getter.py", line 82, in get_url
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 162, in recv_attach
    self.func(self.identifier, surface)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 162, in recv_attach
    self.overlay_draw(None, surface_ctx)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 220, in overlay_draw
    self.redraw()
    current_y = self.draw_text(current_y, message)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 265, in draw_text
    self.redraw()
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/overlay.py", line 226, in redraw
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/overlay.py", line 226, in redraw
DEBUG:urllib3.connectionpool:https://cdn.discordapp.com:443 "GET /attachments/709875150484406402/899071721993281606/unknown.png HTTP/1.1" 200 10928
    self.overlay_draw(None, surface_ctx)
    self.context.fill()
cairo.Error: no current point defined
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 220, in overlay_draw
    self.overlay_draw(None, surface_ctx)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 208, in overlay_draw
    current_y = self.draw_text(current_y, message)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 263, in draw_text
    self.col(self.bg_col)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/overlay.py", line 264, in col
DEBUG:urllib3.connectionpool:https://cdn.discordapp.com:443 "GET /attachments/709875150484406402/899071721993281606/unknown.png HTTP/1.1" 200 10928
DEBUG:urllib3.connectionpool:https://cdn.discordapp.com:443 "GET /attachments/709875150484406402/899071721993281606/unknown.png HTTP/1.1" 200 10928
    self.context.set_source_rgba(col[0], col[1], col[2], col[3] * alpha)
cairo.Error: no current point defined
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 41 8192
    current_y = self.draw_attach(current_y, url)
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/text_overlay.py", line 243, in draw_attach
    _new_w, new_h = draw_img_to_rect(
  File "/home/josh/.local/lib/python3.9/site-packages/discover_overlay/image_getter.py", line 179, in draw_img_to_rect
    ctx.rectangle(0, 0, img.get_width(), img.get_height())
cairo.Error: no current point defined
```

**Comment by trigg** [comment]
As with most errors. I'm currently unable to reproduce this I'm experiencing an unrelated issue!

I'm looking into it.
