### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by KingisFire** [trigg/Discover#289]
Hi, I'm trying to launch the app but got a syntax error.
```
(base) maxime@pc-maxime:~$ discover-overlay
Traceback (most recent call last):
  File "/home/maxime/anaconda3/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/home/maxime/anaconda3/lib/python3.7/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/maxime/anaconda3/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 166
    if any((match := pattern.match(x)) for x in data):
                  ^
SyntaxError: invalid syntax
```
And with a most recent environment, an import error :
```
(IAAA) maxime@pc-maxime:~$ discover-overlay 
Traceback (most recent call last):
  File "/home/maxime/anaconda3/envs/IAAA/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/home/maxime/anaconda3/envs/IAAA/lib/python3.8/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/maxime/anaconda3/envs/IAAA/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 23, in <module>
    import gi
  File "/home/maxime/anaconda3/envs/IAAA/lib/python3.8/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /home/maxime/anaconda3/envs/IAAA/lib/python3.8/site-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so: undefined symbol: ffi_call, version LIBFFI_BASE_7.0
```

How can I fix this ?

**Comment by trigg** [comment]
Sorry just getting around to this. I suspect the first issue is that you need a newer python version (personally all testing is done on 3.10) 

The 2nd looks like python gi is misconfigured. How are you installing this?
