### ISSUE TITLE
Issues on Kubuntu 23.04

### ISSUE THREAD

**Issue by dsk0** [trigg/Discover#305]
**Steps to Reproduce**
I performed the following to install: 
1. `apt install python3-gi python3-gi-cairo libappindicator3-dev -y`
2. Tried `python3 -m pip install discover-overlay` but it complained and asked for `libgirepository1.0-dev`
3. Did `sudo apt install libgirepository1.0-dev`
4. Ran `python3 -m pip install discover-overlay` successfully as so: 
<pre>$ python3 -m pip install discover-overlay
Collecting discover-overlay
  Using cached discover_overlay-0.6.5-py3-none-any.whl (123 kB)
Collecting PyGObject>=3.22
  Using cached PyGObject-3.44.1.tar.gz (720 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pillow in ./programs/anaconda3/lib/python3.10/site-packages (from discover-overlay) (9.4.0)
Collecting python-xlib
  Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Requirement already satisfied: requests in ./programs/anaconda3/lib/python3.10/site-packages (from discover-overlay) (2.29.0)
Requirement already satisfied: setuptools in ./programs/anaconda3/lib/python3.10/site-packages (from discover-overlay) (65.6.3)
Collecting websocket-client
  Using cached websocket_client-1.6.0-py3-none-any.whl (56 kB)
Collecting pyxdg
  Using cached pyxdg-0.28-py2.py3-none-any.whl (49 kB)
Collecting pycairo>=1.16.0
  Using cached pycairo-1.24.0-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: six>=1.10.0 in ./programs/anaconda3/lib/python3.10/site-packages (from python-xlib->discover-overlay) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./programs/anaconda3/lib/python3.10/site-packages (from requests->discover-overlay) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./programs/anaconda3/lib/python3.10/site-packages (from requests->discover-overlay) (2023.5.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./programs/anaconda3/lib/python3.10/site-packages (from requests->discover-overlay) (1.26.16)
Requirement already satisfied: idna<4,>=2.5 in ./programs/anaconda3/lib/python3.10/site-packages (from requests->discover-overlay) (3.4)
Building wheels for collected packages: PyGObject
  Building wheel for PyGObject (pyproject.toml) ... done
  Created wheel for PyGObject: filename=PyGObject-3.44.1-cp310-cp310-linux_x86_64.whl size=261650 sha256=8cd09bef2e73085298b30e9befd4705dcfcf2fb0679d1d7b3cdb8edc381ae369
  Stored in directory: /home/nero/.cache/pip/wheels/75/f7/97/cd86552b7816f253292890ff1eb10a2fae90a3375a0b4286a1
Successfully built PyGObject
Installing collected packages: pyxdg, websocket-client, python-xlib, pycairo, PyGObject, discover-overlay
Successfully installed PyGObject-3.44.1 discover-overlay-0.6.5 pycairo-1.24.0 python-xlib-0.33 pyxdg-0.28 websocket-client-1.6.0</pre>

**When attempting to run**
The following error occurrs:

<pre>
$ discover-overlay 
Traceback (most recent call last):
  File "/home/nero/programs/anaconda3/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/home/nero/programs/anaconda3/lib/python3.10/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/nero/programs/anaconda3/lib/python3.10/site-packages/discover_overlay/discover_overlay.py", line 23, in <module>
    import gi
  File "/home/nero/programs/anaconda3/lib/python3.10/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgirepository-1.0.so.1: undefined symbol: g_string_free_and_steal
</pre>

**Additional context**
<pre>$ python --version
Python 3.10.9**</pre>

What can I try?

Thanks

**Comment by Bqleine** [comment]
Try updating your packages and make sure glib is installed
