### ISSUE TITLE
Flathub package is currently crashing on Plasma Wayland

### ISSUE THREAD

**Issue by dev-rfc** [trigg/Discover#319]
Just open the application:

```
[rfc@rfc-desktop ~]$ flatpak run io.github.trigg.discover_overlay 
INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.6.7

** (discover-overlay:2): WARNING **: 21:49:32.480: gtk-layer-shell v0.7.0 may not work on GTK v3.24.39. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
ERROR - discover_overlay.image_getter - File not found: /home/rfc/.local/share/icons/hicolor/256x256/apps/discover-overlay-default.png
ERROR - discover_overlay.image_getter - File not found: /usr/share/icons/hicolor/256x256/apps/discover-overlay-default.png
ERROR - discover_overlay.image_getter - File not found: /home/rfc/.local/share/icons/hicolor/256x256/apps/discover-overlay-default.png
ERROR - discover_overlay.image_getter - File not found: /usr/share/icons/hicolor/256x256/apps/discover-overlay-default.png
INFO - discover_overlay.discord_connector - ID is XXXXXXXXXXXXXXX
INFO - discover_overlay.discord_connector - Logged in as rfc.
```

And then, after a few seconds, the application closes itself.

```[rfc@rfc-desktop ~]$ flatpak --version 
Flatpak 1.15.6
```

Also, probably known issue, but there is no tray icon as well.

**Comment by trigg** [comment]
Nothing in the log suggests it crashed, the layer shell warning is expected at this point.

I'll do some tests later today but for completeness sake, what OS are you using?

> Also, probably known issue, but there is no tray icon as well.
[Aye, that one is known](https://github.com/flathub/io.github.trigg.discover_overlay/issues/2) and I wish I could do more about it.

**Comment by trigg** [comment]
A newer flatpak has been released since this issue, can you confirm or deny this still happens on version 0.7.0?

> But there is no tray icon there as well.

Unfortunately I have no way to get tray icons in flatpak version right now. [I'm tracking it here](https://github.com/flathub/io.github.trigg.discover_overlay/issues/2), but it is beyond my understanding of flatpak

**Comment by trigg** [comment]
Thanks for the follow up, I'll have to find a way to reproduce this

**Comment by ong-andrew** [comment]
Facing the same problem. Might be due to a Discord update?

```
$ discover-overlay
INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.7.0
ERROR - discover_overlay.image_getter - File not found: 
ERROR - discover_overlay.image_getter - File not found: 
ERROR - discover_overlay.image_getter - File not found: 
INFO - discover_overlay.discord_connector - Connecting...
INFO - discover_overlay.discord_connector - Scheduled a reconnect
ERROR - discover_overlay.image_getter - File not found: 
ERROR - discover_overlay.image_getter - File not found: 
ERROR - discover_overlay.image_getter - File not found: 
INFO - discover_overlay.discord_connector - Connecting...
INFO - discover_overlay.discord_connector - Scheduled a reconnect
INFO - discover_overlay.discord_connector - Connecting...
INFO - discover_overlay.discord_connector - Scheduled a reconnect
```

**Comment by trigg** [comment]
I've tried with plasma, using flatpak discover-overlay with both flatpak and arch packaged discord and I've been unable to reproduce this as of yet.

**Comment by jonstump** [comment]
I'm also seeing a similar issue, but it only seems to happen with the configuration app. I'm on Linux Mint and it is a fresh install. This is not the first time recently I've run into odd issues with flatpaks. Is it possible that there might be a larger issue at play with flatpaks and fresh linux installs? Just a thought looking at both threads. The other app I ran into an issue with for the sake of reference is supersonic. [Original ticket here](https://github.com/dweymouth/supersonic/issues/365).

```
me@local:~$ flatpak run io.github.trigg.discover_overlay -c
Gtk-Message: 20:17:27.734: Failed to load module "xapp-gtk3-module"
INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.7.3
ERROR - discover_overlay.settings_window - No icon found in theme
INFO - discover_overlay.autostart - Autostart info : desktop None auto None
INFO - discover_overlay.autostart - Autostart info : desktop None auto None
INFO - discover_overlay.settings_window - Falling back to Systray : Namespace AppIndicator3 not available
ERROR - discover_overlay.discover_overlay - 'voice_anchor_to_edge_button'
ERROR - discover_overlay.discover_overlay - Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/discover_overlay/discover_overlay.py", line 534, in entrypoint
    settings = MainSettingsWindow(
  File "/app/lib/python3.10/site-packages/discover_overlay/settings_window.py", line 171, in __init__
    self.read_config()
  File "/app/lib/python3.10/site-packages/discover_overlay/settings_window.py", line 683, in read_config
    self.widget['voice_anchor_to_edge_button'].set_sensitive(False)
KeyError: 'voice_anchor_to_edge_button'

```
