### ISSUE TITLE
Program crashes when changing avatar size while present

### ISSUE THREAD

**Issue by luni3359** [trigg/Discover#52]
I was fiddling with the settings and found that changing the avatar size makes the program crash, sometimes the first time, always the second time you add/decrement the value.

https://github.com/trigg/Discover/blob/7e5334c72a7ced06c5c79b6c6b285c392b0c8611/discover_overlay/voice_overlay.py#L190-L198

``pix`` is ``None`` on line 194, but then when ``draw_avatar_pix`` is run, ``self.def_avatar`` is also ``None``, so it throws the following error:
```
Traceback (most recent call last):
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 124, in draw
    self.do_draw(context)
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 154, in do_draw
    self.draw_avatar(context, user, rh)
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 198, in draw_avatar
    self.draw_avatar_pix(
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 254, in draw_avatar_pix
    Gdk.cairo_set_source_pixbuf(context, pixbuf, x, y)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 124, in draw
    self.do_draw(context)
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 154, in do_draw
    self.draw_avatar(context, user, rh)
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 198, in draw_avatar
    self.draw_avatar_pix(
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 254, in draw_avatar_pix
    Gdk.cairo_set_source_pixbuf(context, pixbuf, x, y)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 154, in do_draw
    self.draw_avatar(context, user, rh)
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 198, in draw_avatar
    self.draw_avatar_pix(
  File "/home/user/Projects/Discover/discover_overlay/voice_overlay.py", line 254, in draw_avatar_pix
    Gdk.cairo_set_source_pixbuf(context, pixbuf, x, y)
TypeError: Argument 1 does not allow None as a value
python3: ../../../../src/cairo.c:524: cairo_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)' failed.
```

**Comment by luni3359** [comment]
You need to be in a voice channel for this bug to occur.

**Comment by trigg** [comment]
Ah my first threading error!

Ok cool that was foolish of me to assume it worked every time.
