### ISSUE TITLE
Crash when starting with autostart disabled

### ISSUE THREAD

**Issue by MurdoMaclachlan** [trigg/Discover#54]
Me again, experiencing any and all bugs that can possibly happen! Updated to release version 0.2 to play around with it a bit, but it seems to have introduced a new launch crash, giving the following output:
```
INFO:root:Autostart info : desktop /home/murdo/.local/share/applications/discover_overlay.desktop auto None
Traceback (most recent call last):
  File "/usr/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/murdo/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 125, in entrypoint
    discover.main()
  File "/home/murdo/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 109, in main
    self.create_gui()
  File "/home/murdo/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 46, in create_gui
    self.menu = self.make_menu()
  File "/home/murdo/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 74, in make_menu
    autostart_opt.set_active(self.a.is_auto())
TypeError: Argument 1 does not allow None as a value
```
I'm assuming it's some kind of error to do with not specifying any arguments, either in the launch command or somewhere in the code where it expects them.

**Comment by MurdoMaclachlan** [comment]
I made a fork to test a theory, and changing `return True if self.auto else None` to `return True if self.auto else None` in autostart.py fixed this crash for me. With the change, everything works perfectly again. I'm fairly new to repos with more than one person working on them, but I made a [pull request for this fix](https://github.com/trigg/Discover/pull/55). Hopefully, it's not the wrong way to go about it.
