### ISSUE TITLE
Application fails to start

### ISSUE THREAD

**Issue by DBerke** [trigg/Discover#65]
Got a frustratingly-vague bug for you: I installed with `pip install discover-overlay` (pip = pip3, Python 3.7), ran `discover-overlay`, and it gave me the following error. I'm on Debian 10 stable running Cinnamon as my DE; let me know if you want any other information.

```shell
/home$ discover-overlay 
INFO:root:Autostart info : desktop /home/daniel/.local/share/applications/discover_overlay.desktop auto None
Traceback (most recent call last):
  File "/home/daniel/.local/bin/discover-overlay", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/daniel/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 125, in entrypoint
    discover.main()
  File "/home/daniel/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 109, in main
    self.create_gui()
  File "/home/daniel/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 46, in create_gui
    self.menu = self.make_menu()
  File "/home/daniel/.local/lib/python3.7/site-packages/discover_overlay/discover_overlay.py", line 74, in make_menu
    autostart_opt.set_active(self.a.is_auto())
TypeError: Argument 1 does not allow None as a value
```

**Comment by MurdoMaclachlan** [comment]
This bug should have been fixed with #55. Out of interest, if you go into the files you downloaded, what's the last line in autostart.py?

**Comment by MurdoMaclachlan** [comment]
I had a look at the latest files available on pypi.org, and it seems the official pip is not up to date with the #55 fix. Could you try using the latest testing installation:

```
git clone https://github.com/trigg/Discover.git
cd Discover
python3 -m pip install .
```

and see if you still get the crash?

**Comment by trigg** [comment]
PyPi only lists 'stable' versions so we'd need to promote another release as 0.2.1

**Comment by trigg** [comment]
A new stable has been tagged. Failing this it's possible to tell pip to install specific versions of things so v0.2 is still stable

**Comment by DBerke** [comment]
Hey there, forgot to come back to comment on this, but version 0.2.2 works for me now.

**Comment by Toni500github** [comment]
hi, i'm getting this issue with the AUR package, both stable and latest
```py
[toni@arch2 ~/.cache/yay]$ discover-overlay -c         
INFO - discover_overlay.discover_overlay - Starting Discover Overlay: 0.6.6
INFO - discover_overlay.autostart - Autostart info : desktop /usr/share/applications/discover_overlay.desktop auto None
INFO - discover_overlay.autostart - Autostart info : desktop /usr/share/applications/discover_overlay_configure.desktop auto None
ERROR - discover_overlay.discover_overlay - Argument 1 does not allow None as a value
ERROR - discover_overlay.discover_overlay - Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/discover_overlay/discover_overlay.py", line 520, in entrypoint
    settings = MainSettingsWindow(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/discover_overlay/settings_window.py", line 143, in __init__
    self.read_config()
  File "/usr/lib/python3.11/site-packages/discover_overlay/settings_window.py", line 299, in read_config
    self.widget['voice_title_font'].set_font(font)
TypeError: Argument 1 does not allow None as a value

```
