### ISSUE TITLE
Bad imports after last few commits

### ISSUE THREAD

**Issue by bytechef** [trigg/Discover#67]
Latest few commits are preventing me from running.

```Bash
~/Computing/Discover $ cat run.sh
python -m pip install .
~/.local/bin/discover-overlay
~/Computing/Discover $ ./run.sh  
Defaulting to user installation because normal site-packages is not writeable
Processing /run/media/cook/DATA/Computing/Discover
Requirement already satisfied: PyGObject>=3.22 in /usr/lib/python3.8/site-packages (from discover-overlay==0.2.2) (3.36.1)
Requirement already satisfied: websocket-client in /home/cook/.local/lib/python3.8/site-packages (from discover-overlay==0.2.2) (0.57.0)
Requirement already satisfied: pyxdg in /home/cook/.local/lib/python3.8/site-packages (from discover-overlay==0.2.2) (0.26)
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (from discover-overlay==0.2.2) (2.24.0)
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from websocket-client->discover-overlay==0.2.2) (1.15.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.8/site-packages (from requests->discover-overlay==0.2.2) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.8/site-packages (from requests->discover-overlay==0.2.2) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from requests->discover-overlay==0.2.2) (1.25.10)
Using legacy setup.py install for discover-overlay, since package 'wheel' is not installed.
Installing collected packages: discover-overlay
  Attempting uninstall: discover-overlay
    Found existing installation: discover-overlay 0.2.2
    Uninstalling discover-overlay-0.2.2:
      Successfully uninstalled discover-overlay-0.2.2
    Running setup.py install for discover-overlay ... done
Successfully installed discover-overlay-0.2.2
INFO:root:Autostart info : desktop /home/cook/.local/share/applications/discover_overlay.desktop auto /home/cook/.config/autostart/discover_overlay.desktop
Traceback (most recent call last):
  File "/home/cook/.local/bin/discover-overlay", line 33, in <module>
    sys.exit(load_entry_point('discover-overlay==0.2.2', 'console_scripts', 'discover-overlay')())
  File "/home/cook/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 108, in entrypoint
    discover = Discover()
  File "/home/cook/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 30, in __init__
    self.create_gui()
  File "/home/cook/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 47, in create_gui
    self.voice_settings = VoiceSettingsWindow(self.voice_overlay)
  File "/home/cook/.local/lib/python3.8/site-packages/discover_overlay/voice_settings.py", line 19, in __init__
    self.init_config()
  File "/home/cook/.local/lib/python3.8/site-packages/discover_overlay/settings.py", line 20, in init_config
    self.read_config()
  File "/home/cook/.local/lib/python3.8/site-packages/discover_overlay/voice_settings.py", line 91, in read_config
    desc = Pango.FontDescription.from_string(self.font)
NameError: name 'Pango' is not defined
```

Using latest master

**Comment by bytechef** [comment]
Fixed by changing:
```
from gi.repository import Gtk, Gdk
```
to
```
from gi.repository import Gtk, Gdk, Pango
```
in voice_settings.py

**Comment by trigg** [comment]
Forgot to push that commit. My apologies
