### ISSUE TITLE
No GUI Settings

### ISSUE THREAD

**Issue by sudofry** [trigg/Discover#81]
The avatars display on the right side when I join a voice channel. But I can't seem to get an interface with the settings to show up.

**Comment by trigg** [comment]
Are you on latest stable or testing version? Do you not get a system tray icon?

**Comment by sudofry** [comment]
I am on the stable version. There is a system tray icon. But I have to kill it with a task manager because there's no indication that it's even running unless I'm in a voice channel.

**Comment by trigg** [comment]
Can you right click on it?

**Comment by sudofry** [comment]
![Screenshot from 2020-10-11 13-11-53](https://user-images.githubusercontent.com/72702921/95685035-67076c00-0bc3-11eb-8821-8bd58b634315.png)

**Comment by sudofry** [comment]
That's what right click gives me.

**Comment by trigg** [comment]
Ah, that's the launcher, not a system tray. Guessing you're on Gnome then?

**Comment by sudofry** [comment]
Yes yes.

**Comment by trigg** [comment]
Ok, this was fixed in #75 

Either install testing or wait until we push a new stable version and grab that.

**Comment by sudofry** [comment]
Ok. Thank you. Sorry for the misunderstanding about the system tray.

**Comment by trigg** [comment]
All good! Terminology is easy to misunderstand :)

**Comment by fugohan** [comment]
I can't open the settings. 

I'm using gnome with x11 and get this output when I try ```discover-overlay -c```

```
Traceback (most recent call last):
  File "/home/fugohan/.local/bin/discover-overlay", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/fugohan/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 209, in entrypoint
    Discover(rpc_file, line)
  File "/home/fugohan/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 41, in __init__
    self.do_args(args, True)
  File "/home/fugohan/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 81, in do_args
    self.show_settings()
  File "/home/fugohan/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 161, in show_settings
    self.settings.present_settings()
AttributeError: 'Discover' object has no attribute 'settings'
```
