### ISSUE TITLE
Current latest fails to launch on Gnome

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#92]
Looks like some of the latest Wayland stuff breaks it on X / gnome. 
`$ discover-overlay 
Traceback (most recent call last):
  File "/home/craig/.local/bin/discover-overlay", line 5, in <module>
    from discover_overlay.discover_overlay import entrypoint
  File "/home/craig/.local/lib/python3.8/site-packages/discover_overlay/__init__.py", line 14, in <module>
    from .discover_overlay import *
  File "/home/craig/.local/lib/python3.8/site-packages/discover_overlay/discover_overlay.py", line 18, in <module>
    from .settings_window import MainSettingsWindow
  File "/home/craig/.local/lib/python3.8/site-packages/discover_overlay/settings_window.py", line 13, in <module>
    from .voice_settings import VoiceSettingsWindow
  File "/home/craig/.local/lib/python3.8/site-packages/discover_overlay/voice_settings.py", line 17, in <module>
    from .draggable_window_wayland import DraggableWindowWayland
  File "/home/craig/.local/lib/python3.8/site-packages/discover_overlay/draggable_window_wayland.py", line 18, in <module>
    from gi.repository import Gtk, Gdk, GtkLayerShell
  File "/usr/lib/python3.8/site-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GtkLayerShell, introspection typelib not found`
`

**Comment by trigg** [comment]
You're missing the library for Gtk layer shell. We need to work around this as it won't be there for most X11 users

**Comment by midget3111** [comment]
Aha, ta. I'll update readme with deps
